# Generated by Django 4.1.1 on 2022-09-28 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_likedsongs_musics_list_music_music_id_music_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_listeners', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='music',
            old_name='header_image',
            new_name='thumnail',
        ),
        migrations.RemoveField(
            model_name='likedsongs',
            name='musics_list',
        ),
        migrations.AddField(
            model_name='likedsongs',
            name='musics',
            field=models.ManyToManyField(null=True, to='base.music'),
        ),
        migrations.AddField(
            model_name='music',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='user_playlists',
            name='playlists',
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('public', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('musics', models.ManyToManyField(null=True, to='base.music')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('musics', models.ManyToManyField(null=True, to='base.music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='base.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_playlists',
            name='playlists',
            field=models.ManyToManyField(null=True, to='base.playlist'),
        ),
    ]
