# Generated by Django 4.1.1 on 2022-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_author_rename_header_image_music_thumnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musics',
            field=models.ManyToManyField(to='base.music'),
        ),
        migrations.AlterField(
            model_name='likedsongs',
            name='musics',
            field=models.ManyToManyField(to='base.music'),
        ),
        migrations.AlterField(
            model_name='user_playlists',
            name='playlists',
            field=models.ManyToManyField(to='base.playlist'),
        ),
    ]
