# Generated by Django 4.1.1 on 2022-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_album_musics_alter_likedsongs_musics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(to='base.music'),
        ),
    ]
