# Generated by Django 4.1.1 on 2022-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_author_user_playlist_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='uni_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='My playlist', max_length=100),
        ),
    ]
