# Generated by Django 4.1.1 on 2022-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_playlist_uni_id_alter_music_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
