# Generated by Django 4.1.1 on 2022-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_recently_played_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='thumnail',
            field=models.ImageField(default='images\\photo_2022-08-24_01-12-05_lyHjP44.jpg', null=True, upload_to='images/'),
        ),
    ]
