# Generated by Django 4.1.1 on 2022-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_music_id_music_uni_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uni_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
