# Generated by Django 4.1.1 on 2022-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_author_uni_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
