# Generated by Django 4.1.1 on 2022-10-20 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_author_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.playlist')),
                ('last_track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.music')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
