# Generated by Django 4.1.1 on 2022-10-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_likedsongs_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='uni_id',
            field=models.CharField(default='s1BYFwcaE5MUKyQNgoRf', max_length=20, null=True),
        ),
    ]
