# Generated by Django 4.1.1 on 2022-11-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_alter_music_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedsongs',
            name='uni_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='uni_id',
            field=models.CharField(default='Dze8dBzdhNDxBqjcehUM', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FollowedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(max_length=30)),
                ('artists', models.ManyToManyField(to='base.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
