# Generated by Django 4.1.1 on 2022-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_likedsongs_uni_id_alter_music_uni_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_playlists',
            name='uni_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='uni_id',
            field=models.CharField(default='eXPfNLsXM61h6Z6dR6TT', max_length=20, null=True),
        ),
    ]
