from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('playlist/<str:playlist_id>', views.collection, name='collection'),
    path('collection/tracks', views.librarytracks, name='collectiontracks'),
    path('artist/<str:artist_id>', views.ArtistPage, name='ArtistPage'),
    path('create/playlist/', views.CreatePlaylist, name='CreatePlaylist'),
    path('create2/playlist/<str:name>', views.CreatePlaylist2, name='create_playlist2'),
    path('collection/playlists', views.library, name='libraryPlaylists'),
    path('collection/artists', views.library, name='libraryArtists'),
    path('collection/albums', views.library, name='libraryAlbums'),
    path('get/artist/<str:artist_id>/info', views.ArtistInfo, name= 'ArtistInfo'),
    path('get/playlist/<str:playlist_id>/info', views.GetPlaylistInfo, name='GetPlaylistInfo'),
    path('get/home/content', views.GetHomeContent, name='GetHomeContent'),
    path('get/music/<str:music_id>/info', views.GetTrackInfo, name='GetTrackInfo'),
    path('get/playlists/info', views.GetPlaylists, name='get_playlists'),
    path('get/RecPlaylists/info', views.RecPlaylists, name='RecPlaylists'),
    path('get/Fartists/info', views.FollowedArtistsInfo, name='get_artists'),
    path('track/<str:music_id>', views.TrackPage, name='trackpage'),
    path('likedsongs/<str:action>/track/<str:track_id>', views.UpdateLikedSongs, name="UpdateLikedSongs"),
    path('likedsongs/get/tracklist', views.GetLikedSongsList, name="get_liked_songs_list"),
    path('artists/get/list', views.FollowedArtistsList, name="FollowedArtistsList"),
    path('artists/<str:action>/artist/<str:artist_id>', views.updateFollowedArtistslist, name="updateFollowedArtistslist"),
    path('likedsongs/get/info', views.GetLikedSongs, name='GetLikedSongs'),
    path("search/", views.RawSearch, name='pagesearch'),
    path("search/<str:question>", views.Search, name='search'),
    path('betasearch/<str:question>', views.BetaSearch, name='betasearch'),
    path('delete/playlist/<str:playlist_id>', views.DeletePlaylist, name='delete_playlist'),
    path('<str:action>/track/<str:track_id>/playlist/<str:playlist_id>', views.UpdatePlaylistList, name='UpdatePlaylistList'),
    path('library/<str:action>/playlist/<str:playlist_id>', views.UpdateLibrary, name='UpdateLibrary'),
    path('history/last/<str:type>/<str:id>', views.HistoryUpdate, name='history_update'),
    path('history/get/last/', views.GetHistory, name='history_get'),
    path('playlist/<str:playlist_id>/make/<str:privacytype>', views.ChangePlaylistPrivacy, name='ChangePlaylistPrivacy'),
    path("register/", views.RegisterPage, name='signup_page_default'),
    path("login/",views.LoginPage, name='login_page_default'),
]
